export const students = [
  {
    name: "Ian Baker",
    age: 23,
    gender: "Male",
    courseName: "ICT",
    id: "2020-ICT-09",
    profilePic: require('../assets/profilepic/9.jpg'),
  },
  {
    name: "Julia Davis",
    age: 21,
    gender: "Female",
    courseName: "CSE",
    id: "2020-CSE-10",
    profilePic: require('../assets/profilepic/10.jpg'),
  },
  {
    name: "Kevin Morris",
    age: 22,
    gender: "Male",
    courseName: "ECE",
    id: "2020-ECE-11",
    profilePic: require('../assets/profilepic/11.jpg'),
  },
  {
    name: "Sophia Wilson",
    age: 20,
    gender: "Female",
    courseName: "IT",
    id: "2020-IT-12",
    profilePic: require('../assets/profilepic/12.jpg'),
  },
  {
    name: "Daniel Carter",
    age: 24,
    gender: "Male",
    courseName: "Mechanical",
    id: "2020-ME-13",
    profilePic: require('../assets/profilepic/13.jpg'),
  },
  {
    name: "Emma Johnson",
    age: 21,
    gender: "Female",
    courseName: "Civil",
    id: "2020-CV-14",
    profilePic: require('../assets/profilepic/14.jpg'),
  },
  {
    name: "James Brown",
    age: 23,
    gender: "Male",
    courseName: "Electrical",
    id: "2020-EE-15",
    profilePic: require('../assets/profilepic/15.jpg'),
  },
  {
    name: "Olivia Harris",
    age: 22,
    gender: "Female",
    courseName: "ICT",
    id: "2020-ICT-16",
    profilePic: require('../assets/profilepic/16.jpg'),
  },
  {
    name: "Liam Evans",
    age: 25,
    gender: "Male",
    courseName: "CSE",
    id: "2020-CSE-17",
    profilePic: require('../assets/profilepic/17.jpg'),
  },
  {
    name: "Mia Scott",
    age: 22,
    gender: "Female",
    courseName: "Electronics",
    id: "2020-EC-18",
    profilePic: require('../assets/profilepic/18.jpg'),
  }
];